"""Make date of birth optional

Revision ID: 1d5c9eb37a6c
Revises: 6a09902e4ffe
Create Date: 2025-07-17 17:48:17.905850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d5c9eb37a6c"
down_revision: Union[str, None] = "6a09902e4ffe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "date_of_birth", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "date_of_birth", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
